algoritmo "numeros_iguais"
var

      // Escreva um algoritmo que leia dois números e escreva, “são iguais”, caso estes números sejam realmente iguais.

      n1, n2: inteiro

inicio

      escreval("Digite o primeiro numero: ")
      leia(n1)
      escreval("Digite o segundo numero: ")
      leia(n2)
      se (n1 = n2) entao
         escreval("Os números são iguais.")
      fimse

fimalgoritmo
